version: '3'
services:
  elasticsearch:
    container_name: first-elasticsearch
    image: elasticsearch:$ELASTIC_VERSION
    env_file: 
      - .env
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
      - cluster.routing.allocation.disk.threshold_enabled=false # disable disk threshold (https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - $ELASTIC_PORT:9200
    networks: ['stack']

  # kibana:
  #   image: kibana:$ELASTIC_VERSION
  #   env_file: 
  #     - .env
  #   environment:
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
  #   ports: ['5601:5601']
  #   networks: ['stack']
  #   links: ['elasticsearch']
  #   depends_on: ['elasticsearch']

networks:
  stack: {}