version: '3'

services:
  milvus:
    image: milvusdb/milvus:1.1.1-gpu-d061621-330cc6
    container_name: first-milvus_gpu_1.1.1
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - $DOCKER_VOLUME_DIRECTORY/milvus/db:/var/lib/milvus/db
      - $DOCKER_VOLUME_DIRECTORY/milvus/conf:/var/lib/milvus/conf
      - $DOCKER_VOLUME_DIRECTORY/milvus/logs:/var/lib/milvus/logs
      - $DOCKER_VOLUME_DIRECTORY/milvus/wal:/var/lib/milvus/wal
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
